HairSalon/Models/Client.cs
using System.Collections.Generic;

namespace Salon.Models
{
  public class Client
  {
    public int ClientId { get; set; }
    public string ClientName { get; set; }
    public int StylistId { get; set; }
    public virtual Stylist Stylist { get; set; }
  }
}

HairSalon/Models/SalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace Salon.Models
{
  public class SalonContext : DbContext
  {
    public virtual DbSet<Stylist> Stylists { get; set; }
    public virtual DbSet<Client> Clients { get; set; }

    public SalonContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace Salon.Models
{
  public class Stylist
  {
    public int StylistId { get; set; }
    public string StylistName { get; set; }
    public int ClientId { get; set; }
    public virtual ICollection<Client> ClientList { get; set; }

    public Stylist()
    {
      this.ClientList = new HashSet<Client>();
    }
  }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using Salon.Models;

namespace Salon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly SalonContext _db;

    public ClientsController(SalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Client> model = _db.Clients.Include(client => client.Stylist).ToList();
      return View(model);
    }

    public ActionResult Details(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    public ActionResult Create()
    {
      SelectList stylistList = new SelectList(_db.Stylists, "StylistId", "StylistName");
      ViewBag.StylistId = (stylistList.Count() == 0) ? null : stylistList;
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "StylistName");
      return View(thisClient);
    }

    [HttpPost]
    public ActionResult Edit(Client client)
    {
      _db.Entry(client).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      _db.Clients.Remove(thisClient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Salon.Models;
using System.Collections.Generic;

namespace Salon.Collections
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using Salon.Models;

namespace Salon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly SalonContext _db;

    public StylistsController(SalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Details(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    public ActionResult Create()
    {
      ViewBag.ClientId = new SelectList(_db.Clients, "ClientId", "ClientName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist stylist)
    {
      _db.Entry(stylist).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      _db.Stylists.Remove(thisStylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@using Salon.Models;
@model Salon.Models.Client;

<h2>Add a new Client</h2>

@if(ViewBag.StylistId == null)
{
  <p>you need a Stylists first</p>
  <p>@Html.ActionLink("Add new Stylist", "Create", "Stylists")</p>
} else
{
  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.ClientName)
    @Html.TextBoxFor(model => model.ClientName)

    @Html.LabelFor(model => model.Stylist)
    @Html.DropDownList("StylistId")

    <input type="submit" value="Add new Client" class="btn btn-default"/>
  }
}
<p>@Html.ActionLink("Show all Clients", "Index")</p>

HairSalon/Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Salon.Models.Client

<h2>Are you sure you want to delete this?</h2>

<h3>Name: @Html.DisplayFor(model => model.ClientName)</h3>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete"/>
}

@Html.ActionLink("Back to List", "Index")

HairSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@using Salon.Models;
@model Salon.Models.Client;

<h2>Client details</h2>
<hr />
<h3>Name: @Html.DisplayFor(model => model.ClientName)</h3>

<p>@Html.ActionLink("Edit Client", "Edit", new { id = Model.ClientId})</p>
<p>@Html.ActionLink("Delete Client", "Delete", new { id = Model.ClientId})</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

HairSalon/Views/Clients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Salon.Models.Client

<h2>Edit</h2>

<h4>Edit this Client : @Html.DisplayFor(model => model.ClientName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ClientId)

  @Html.LabelFor(model => model.ClientName)
  @Html.EditorFor(model => model.ClientName)

  @Html.LabelFor(model => model.Stylist)
  @Html.DropDownList("StylistId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using Salon.Models;
@model List<Salon.Models.Client>;

<h1>Clients</h1>

@if (@Model.Count == 0)
{
  <h3>No Clients have been</h3>
}

@foreach (Client client in Model)
{
  <li>@Html.ActionLink($"{client.ClientName}", "Details", new { id = client.ClientId })</li>
}

<p>@Html.ActionLink("Add new Client", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to the Salon Tracker</h1>

<p>@Html.ActionLink("See all Stylists", "Index", "Stylists")</p>
<p>@Html.ActionLink("See all Clients", "Index", "Clients")</p>

HairSalon/Views/Shared/Footer.cshtml
<div id="footer">Salon Tracker by kiernan beattie</div>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>My Salon!</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" htef="~/css/styles.css">
</head>

<body>
  @RenderBody()
  @await Html.PartialAsync("Footer")
</body>

</html>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model Salon.Models.Stylist

<h2>Add a new Stylist</h2>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.StylistName)
  @Html.TextBoxFor(model => model.StylistName)
  <input type="submit" value="Add new Stylist" />
}

<p>@Html.ActionLink("Show all stylists", "Index")</p>

HairSalon/Views/Stylists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Salon.Models.Stylist

<h2>Are you sure you want to delete this?</h2>

<h3>Name: @Html.DisplayFor(model => model.StylistName)</h3>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Back to Stylists", "Index")

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@using Salon.Models;
@model Salon.Models.Stylist;

<h2>Stylist details</h2>
<hr />
<h3>Name: @Html.DisplayFor(model => model.StylistName)</h3>

<ul>
  @if (@Model.ClientList.Count == 0)
  {
    <p>No clients found</p>
  }

  @foreach (Client client in @Model.ClientList)
  {
    <li>Client: @client.ClientName</li>
  }
</ul>

<p>@Html.ActionLink("Edit Stylist", "Edit", new {id = Model.StylistId})</p>
<p>@Html.ActionLink("Delete Stylist", "Delete", new {id = Model.StylistId})</p>
<p>@Html.ActionLink("Back to Stylists", "Index")</p>

HairSalon/Views/Stylists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Salon.Models.Stylist

<h2>Edit</h2>

<h4>Edit this Stylist: @Html.DisplayFor(model => model.StylistName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StylistId)

  @Html.LabelFor(model => model.StylistName)
  @Html.EditorFor(model => model.StylistName)

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to stylists", "Index")</p>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using Salon.Models;
@model List<Salon.Models.Stylist>;

<h1>Stylist</h1>

@if (@Model.Count == 0)
{
  <h3>No Stylists have been added yet!</h3>
}

@foreach (Stylist stylist in Model)
{
  <li>@Html.ActionLink($"{stylist.StylistName}", "Details", new { id = stylist.StylistId})</li>
}

<p>@Html.ActionLink("Add new Stylist", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>